version: '3'
services:
  backend:
    image: oven/bun:1.1.25
    working_dir: /app
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes: 
      - ./backend:/app
    networks:
      - internal   
    restart: always
    command: bash -c 'bun install && bun --hot index.ts ' #TODO: delete the sleep sentence
  frontend:
    hostname: frontend
    image: oven/bun:1.1.25
    working_dir: /app
    depends_on:
      - backend
    expose:
      - 5173
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    networks:
      - internal
    command: bash -c 'sleep 2 && bun install && bun run dev --host'
    environment:
      - SECRET_BACKEND_URL=backend:3000
    
networks:
  internal: