version: '3'
services:
  frontend:
    hostname: frontend
    image: oven/bun:1.1.25
    working_dir: /app
    expose:
      - 5173
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    networks:
      - internal
    command: bash -c 'sleep 2 && bun install && bun run dev --host'
    
networks:
  internal: