<script lang="ts">
  export let data;
  type EventItem = { nombre:string;organizacion?:string;link:string;tipoEvento?:string;descripcion?:string;fecha?:string;lugar?:string };
  let category: 'events'|'funding' = 'events';
  let eventType = '';
  let selected: EventItem | null = null;
  $: types = [...new Set((data.eventos as EventItem[]).map((item) => item.tipoEvento).filter(Boolean))] as string[];
  $: source = category === 'events' ? data.eventos : data.financiamientos;
  $: items = eventType && category === 'events' ? source.filter((item:EventItem) => item.tipoEvento === eventType) : source;
  $: visibleItems = items.filter((item:EventItem) => item.nombre && item.link);
</script>

<svelte:head><title>Antena Tecnológica · PyMEs</title></svelte:head>
<svelte:window on:keydown={(event)=>event.key==='Escape'&&(selected=null)} />
<main class="antenna page-shell">
  <header><p class="eyebrow">Oportunidades para crecer</p><h1 class="display-title">Antena Tecnológica</h1><p>Eventos, conocimiento y financiación para impulsar la transformación de tu empresa.</p></header>
  <section class="controls"><div class="tabs"><button class:active={category==='events'} on:click={()=>category='events'}>Eventos y conferencias</button><button class:active={category==='funding'} on:click={()=>category='funding'}>Financiaciones</button></div>{#if category==='events'}<label>Tipo de evento<select class="field" bind:value={eventType}><option value="">Todos</option>{#each types as type}<option>{type}</option>{/each}</select></label>{/if}</section>
  {#if data.error}<div class="notice" role="status">{data.error}</div>{/if}
  {#if items.length}
    <section class="cards">{#each visibleItems as item}<button class="event-card" on:click={()=>selected=item}><span class="event-type">{item.tipoEvento||'Oportunidad'}</span><h2>{item.nombre}</h2><span class="organization">{item.organizacion||'Organización no informada'}</span>{#if item.fecha||item.lugar}<span class="metadata">{#if item.fecha}<span>▣ {item.fecha}</span>{/if}{#if item.lugar}<span>⌖ {item.lugar}</span>{/if}</span>{/if}<span class="description">{item.descripcion||'Consultá la fuente para conocer todos los detalles.'}</span><span class="more">Ver información →</span></button>{/each}</section>
  {:else}<div class="empty"><h2>No hay oportunidades disponibles</h2><p>Volvé a intentar más tarde o elegí otra categoría.</p></div>{/if}
  <p class="disclaimer">Información generada y procesada con asistencia de inteligencia artificial. Verificá siempre los datos en la fuente original.</p>
</main>

{#if selected}<div class="modal-backdrop"><article class="modal" role="dialog" aria-modal="true" aria-labelledby="event-title"><button class="close" aria-label="Cerrar" on:click={()=>selected=null}>×</button><span class="event-type">{selected.tipoEvento||'Oportunidad'}</span><h2 id="event-title">{selected.nombre}</h2><p class="organization">{selected.organizacion}</p>{#if selected.fecha}<p>▣ {selected.fecha}</p>{/if}{#if selected.lugar}<p>⌖ {selected.lugar}</p>{/if}<p class="modal-description">{selected.descripcion}</p><a class="btn-primary" href={selected.link} target="_blank" rel="noopener noreferrer">Ver fuente original →</a></article></div>{/if}

<style>
  .antenna{padding-bottom:48px}.antenna>header{padding:52px 5%;background:var(--navy);color:white}.antenna>header .eyebrow{color:var(--lime)}.antenna>header h1{font-size:2.5rem;margin:7px 0}.antenna>header p:last-child{color:#c2ced9;margin:0;max-width:650px}.controls{padding:28px 5%;display:flex;justify-content:space-between;align-items:end;gap:20px}.tabs{display:flex;background:#e9edf0;border-radius:12px;padding:4px}.tabs button{border:0;background:transparent;padding:11px 18px;border-radius:9px;color:#617389;font-weight:700}.tabs button.active{background:var(--navy);color:white}.controls label{font-size:.75rem;text-transform:uppercase;font-weight:800;color:#718198}.controls select{display:block;margin-top:6px;min-width:210px}.cards{padding:0 5%;display:grid;grid-template-columns:repeat(4,1fr);gap:22px}.event-card{min-height:315px;padding:22px;display:flex;flex-direction:column;background:white;border:1px solid #d6dee6;border-radius:17px;box-shadow:0 8px 24px #0a203a0c;transition:.18s;cursor:pointer;color:var(--navy);text-align:left}.event-card:hover{transform:translateY(-3px);box-shadow:0 14px 30px #0a203a18;border-color:#a9bbca}.event-type{align-self:flex-start;background:var(--lime);padding:5px 11px;border-radius:20px;font-size:.68rem;font-weight:800}.cards h2{font-size:1.08rem;line-height:1.25;margin:14px 0 6px}.organization{color:#6f8095;font-size:.78rem}.metadata{display:flex;gap:12px;flex-wrap:wrap;color:#586a80;font-size:.72rem}.description{color:#66778b;font-size:.8rem;line-height:1.5;display:-webkit-box;-webkit-line-clamp:4;line-clamp:4;-webkit-box-orient:vertical;overflow:hidden}.more{margin-top:auto;align-self:flex-start;color:#779800;font-weight:800;padding:8px 0}.notice,.empty{margin:20px 5%;padding:25px;border:1px solid #d5dee6;border-radius:14px;background:white;text-align:center}.disclaimer{text-align:center;color:#75869a;font-size:.73rem;margin:42px 5% 0}.modal-backdrop{position:fixed;inset:0;background:#07182cbb;z-index:3000;display:grid;place-items:center;padding:20px}.modal{position:relative;width:min(620px,100%);max-height:90vh;overflow:auto;background:white;border-radius:20px;padding:34px}.modal h2{margin:18px 0 5px}.modal-description{line-height:1.6;color:#596b80;margin:22px 0}.modal .close{position:absolute;right:18px;top:14px;border:0;background:none;font-size:1.7rem}.modal .btn-primary{width:100%}@media(max-width:1100px){.cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.antenna>header{padding:36px 18px}.antenna>header h1{font-size:2rem}.controls{padding:20px 16px;align-items:stretch;flex-direction:column}.tabs{width:100%}.tabs button{flex:1}.controls label,.controls select{width:100%}.cards{padding:0 16px;grid-template-columns:1fr}.event-card{min-height:260px}.modal{padding:26px 20px}}
</style>
