# Generated by Django 5.2 on 2025-07-01 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PEOPLE', 'People'), ('RESOURCES', 'Resources')], default='PEOPLE')),
                ('name', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('IN_DEFINITION', 'In Definition')], default='IN_PROGRESS', max_length=20)),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('fields', models.JSONField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CampaignResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.JSONField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('ROLE', 'Role'), ('PERMISSION', 'Permission')], default='ROLE', max_length=20)),
                ('fields', models.JSONField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminApi.campaigns')),
            ],
            options={
                'db_table': 'campaign_resources',
            },
        ),
        migrations.CreateModel(
            name='CampaignUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.JSONField(blank=True, null=True)),
                ('handle', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('differential', models.IntegerField(default=0)),
                ('fields', models.JSONField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.campaigns')),
            ],
            options={
                'db_table': 'campaign_users',
            },
        ),
        migrations.CreateModel(
            name='ResourceResourceMappings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resourceresourcemappings_child_set', to='adminApi.campaignresources')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.campaignresources')),
            ],
            options={
                'db_table': 'resource_resource_mappings',
            },
        ),
        migrations.CreateModel(
            name='UserResourceMappings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
                ('state', models.TextField()),
                ('commited', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.campaigns')),
                ('certificant_id', models.ForeignKey(db_column='certificant_id', on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.campaignusers')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.campaignresources')),
                ('certifier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.users')),
            ],
            options={
                'db_table': 'user_resource_mappings',
            },
        ),
        migrations.CreateModel(
            name='ReassignmentRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('state', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.campaigns')),
                ('certificant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.campaignusers')),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.users')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reassignmentrequests_receiver_set', to='adminApi.users')),
            ],
            options={
                'db_table': 'reassignment_requests',
            },
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_admin',
            field=models.ForeignKey(blank=True, db_column='campaign_admin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns_as_admin', to='adminApi.users'),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='default_approver',
            field=models.ForeignKey(blank=True, db_column='default_approver', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns_as_approver', to='adminApi.users'),
        ),
        migrations.CreateModel(
            name='CampaignCertifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.campaigns')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminApi.users')),
            ],
            options={
                'db_table': 'campaign_certifiers',
            },
        ),
    ]
