# Generated by Django 5.2 on 2025-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
