# Generated by Django 5.2 on 2025-07-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0002_campaigns_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('work_type', models.CharField(choices=[('Transformación Digital', 'Transformaciondigital'), ('innovacion', 'Innovacion'), ('Sustentabilidad', 'Sustentabilidad')], default='Transformación Digital', max_length=100)),
                ('enterprise_type', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('latitud', models.TextField(blank=True, null=True)),
                ('longitud', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaignresources',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='resourceresourcemappings',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='resourceresourcemappings',
            name='child',
        ),
        migrations.RemoveField(
            model_name='userresourcemappings',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='campaign_admin',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='default_approver',
        ),
        migrations.RemoveField(
            model_name='campaignusers',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='userresourcemappings',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='reassignmentrequests',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='userresourcemappings',
            name='certificant_id',
        ),
        migrations.RemoveField(
            model_name='reassignmentrequests',
            name='certificant',
        ),
        migrations.RemoveField(
            model_name='reassignmentrequests',
            name='emitter',
        ),
        migrations.RemoveField(
            model_name='reassignmentrequests',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='userresourcemappings',
            name='certifier',
        ),
        migrations.DeleteModel(
            name='CampaignCertifiers',
        ),
        migrations.DeleteModel(
            name='ResourceResourceMappings',
        ),
        migrations.DeleteModel(
            name='CampaignResources',
        ),
        migrations.DeleteModel(
            name='Campaigns',
        ),
        migrations.DeleteModel(
            name='CampaignUsers',
        ),
        migrations.DeleteModel(
            name='ReassignmentRequests',
        ),
        migrations.DeleteModel(
            name='UserResourceMappings',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
